### ISSUE TITLE
Linux 下编译错误

### ISSUE THREAD

**Issue by iven** [gaodayihao/QSanguosha#103]
```
g++ -c -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT -DAUDIO_SUPPORT -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtDeclarative -I/usr/include/qt4 -Iinclude -Isrc/client -Isrc/core -Isrc/dialog -Isrc/package -Isrc/scenario -Isrc/server -Isrc/ui -Isrc/util -Isrc/jsoncpp/include -Iinclude/fmod -Isrc/lua -Iinclude/freetype -I. -I. -o cardeditor.o src/dialog/cardeditor.cpp
src/dialog/cardeditor.cpp: 在构造函数‘AvatarRectItem::AvatarRectItem(qreal, qreal, const QRectF&, int)’中:
src/dialog/cardeditor.cpp:426:1: 警告：‘AvatarRectItem::name_box’ is initialized with itself [-Winit-self]
 AvatarRectItem::AvatarRectItem(qreal width, qreal height, const QRectF &box_rect, int font_size)
 ^
src/dialog/cardeditor.cpp: 在全局域：
src/dialog/cardeditor.cpp:1130:49: 错误：成员函数‘void MainWindow::on_actionCard_editor_triggered()’未在类‘MainWindow’中声明
 void MainWindow::on_actionCard_editor_triggered()
                                                 ^
make: *** [cardeditor.o] 错误 1
```

**Comment by Paracel** [comment]
目测合并的时候把MainWindow那里误删了。。。现在源码编译可能有不少问题，我这周还没时间看。。。

**Comment by iven** [comment]
这样的啊，合并是指新 AI 么？赞！

另外有个不情之请，我在想以后有类似这种大动作的时候，可不可以先放在一个其他的 git 分支里搞，等全弄好了再合并到 master 分支？
因为我在维护 Arch Linux 的 QSanguosha 软件包，是从 git 直接取代码的，总编译不过的话用户会找我麻烦 :P

**Comment by pansz** [comment]
@iven  有个解决办法是，嗯嗯，用你的 github fork 一个专门用于作为 arch linux 稳定版的供应。

每次这边的更新先测试，测试无误了你再拉过去。

因为，实际上并非只是大动作会造成编译不过，而是『经常性』的编译不过。

基本上每次他们提交代码之后我都得稍微再看看 Linux 下面能不能编译，有必要还要改改代码。

**Comment by iven** [comment]
@pansz 汗，这样的工作量可比简单的一条 git branch 命令大多了……小的编译错误我自己就能修了，这种大动作我就无能为力，只能瞪眼了。

**Comment by pansz** [comment]
@iven  与其这样不如每次有稳定版本的时候打个标，你只取打标的版本。而这样的标确实存在，每次发稳定版都有打标的。

**Comment by iven** [comment]
@pansz 对于 Arch 用户来说，稳定版和 git 版是两个不同的包，我说的是 git 版。话说 git 里建个分支容易得要死啊，我看新 AI 那个源不是也维护了一个 dev 分支……

**Comment by BeginnerSlob** [comment]
= =今天我来fix一下。。别急。。

**Comment by WilliamShi** [comment]
fix 好了没有，现在的源码确实在linux下编译不过，我是用的最近的2013-02-24那个编的，可以成功编译

**Comment by iven** [comment]
首先，qmake 的时候提示：

```
WARNING: Failure to find: src/lua/print.c
```

然后 make 的时候提示：

```
src/dialog/halldialog.cpp:141:48: 错误：成员函数‘void Client::roomBegin(const QString&)’未在类‘Client’中声明
 void Client::roomBegin(const QString &begin_str){
                                                ^
src/dialog/halldialog.cpp:150:42: 错误：成员函数‘void Client::room(const QString&)’未在类‘Client’中声明
 void Client::room(const QString &room_str){
                                          ^
src/dialog/halldialog.cpp:166:37: 错误：成员函数‘void Client::roomEnd(const QString&)’未在类‘Client’中声明
 void Client::roomEnd(const QString &){
                                     ^
src/dialog/halldialog.cpp:171:46: 错误：成员函数‘void Client::roomCreated(const QString&)’未在类‘Client’中声明
 void Client::roomCreated(const QString &idstr){
                                              ^
src/dialog/halldialog.cpp:175:47: 错误：成员函数‘void Client::roomError(const QString&)’未在类‘Client’中声明
 void Client::roomError(const QString &errorStr){
                                               ^
src/dialog/halldialog.cpp:187:41: 错误：成员函数‘void Client::hallEntered(const QString&)’未在类‘Client’中声明
 void Client::hallEntered(const QString &){
                                         ^
make: *** [halldialog.o] 错误 1
```

**Comment by Paracel** [comment]
删掉halldialog.cpp

**Comment by iven** [comment]
新的错误：

```
src/server/roomthread.cpp: 在成员函数‘void RoomThread::run3v3(QList<ServerPlayer*>&, QList<ServerPlayer*>&, GameRule*, ServerPl$
src/server/roomthread.cpp:324:75: 错误：对‘GameRule::trigger(TriggerEvent, Room*&, ServerPlayer*&, QVariant)’的调用没有匹配的函$
                 game_rule->trigger(EventPhaseEnd, room, player, QVariant());
                                                                           ^
src/server/roomthread.cpp:324:75: 附注：备选是：
In file included from src/server/roomthread.cpp:4:0:
src/server/gamerule.h:13:18: 附注：virtual bool GameRule::trigger(TriggerEvent, Room*, ServerPlayer*, QVariant&) const
     virtual bool trigger(TriggerEvent triggerEvent, Room *room, ServerPlayer *player, QVariant &data) const;
                  ^
src/server/gamerule.h:13:18: 附注：  no known conversion for argument 4 from ‘QVariant’ to ‘QVariant&’
src/server/roomthread.cpp: 在成员函数‘void RoomThread::actionHulaoPass(ServerPlayer*, QList<ServerPlayer*>, GameRule*, int)’中:
src/server/roomthread.cpp:457:83: 错误：对‘GameRule::trigger(TriggerEvent, Room*&, ServerPlayer*&, QVariant)’的调用没有匹配的函$
                         game_rule->trigger(EventPhaseEnd, room, player, QVariant());
                                                                                   ^
src/server/roomthread.cpp:457:83: 附注：备选是：
In file included from src/server/roomthread.cpp:4:0:
src/server/gamerule.h:13:18: 附注：virtual bool GameRule::trigger(TriggerEvent, Room*, ServerPlayer*, QVariant&) const
     virtual bool trigger(TriggerEvent triggerEvent, Room *room, ServerPlayer *player, QVariant &data) const;
                  ^
src/server/gamerule.h:13:18: 附注：  no known conversion for argument 4 from ‘QVariant’ to ‘QVariant&’
src/server/roomthread.cpp:470:75: 错误：对‘GameRule::trigger(TriggerEvent, Room*&, ServerPlayer*&, QVariant)’的调用没有匹配的函$
                 game_rule->trigger(EventPhaseEnd, room, player, QVariant());
                                                                           ^
src/server/roomthread.cpp:470:75: 附注：备选是：
In file included from src/server/roomthread.cpp:4:0:
src/server/gamerule.h:13:18: 附注：virtual bool GameRule::trigger(TriggerEvent, Room*, ServerPlayer*, QVariant&) const
     virtual bool trigger(TriggerEvent triggerEvent, Room *room, ServerPlayer *player, QVariant &data) const;
                  ^
src/server/gamerule.h:13:18: 附注：  no known conversion for argument 4 from ‘QVariant’ to ‘QVariant&’
src/server/roomthread.cpp: 在成员函数‘void RoomThread::actionNormal(GameRule*)’中:
src/server/roomthread.cpp:498:75: 错误：对‘GameRule::trigger(TriggerEvent, Room*&, ServerPlayer*&, QVariant)’的调用没有匹配的函$
                 game_rule->trigger(EventPhaseEnd, room, player, QVariant());
                                                                           ^
src/server/roomthread.cpp:498:75: 附注：备选是：
In file included from src/server/roomthread.cpp:4:0:
src/server/gamerule.h:13:18: 附注：virtual bool GameRule::trigger(TriggerEvent, Room*, ServerPlayer*, QVariant&) const
     virtual bool trigger(TriggerEvent triggerEvent, Room *room, ServerPlayer *player, QVariant &data) const;
                  ^
src/server/gamerule.h:13:18: 附注：  no known conversion for argument 4 from ‘QVariant’ to ‘QVariant&’
make: *** [roomthread.o] 错误 1
```

**Comment by Paracel** [comment]
这个引用符号是怎么冒出来的= =

**Comment by iven** [comment]
唔，是不是说临时变量不能取引用啊…… = =

**Comment by jackzw8** [comment]
是呀，现在的源码在winxp,Qt4下编译好多错呀！

**Comment by QTurtle** [comment]
@Paracel This is one good example of QT's utter stupidity. Make "QVariant stupid;" a separate line and QT will be happy.

**Comment by WilliamShi** [comment]
error message from make:
                 from ../QSanguosha/src/server/roomthread.cpp:1:
../QSanguosha/src/core/structs.h: In constructor ‘DamageStruct::DamageStruct(const QString&, ServerPlayer_, ServerPlayer_, int, DamageStruct::Nature)’:
../QSanguosha/src/core/structs.h:34:10: warning: ‘DamageStruct::by_user’ will be initialized after [-Wreorder]
../QSanguosha/src/core/structs.h:33:10: warning:   ‘bool DamageStruct::transfer’ [-Wreorder]
../QSanguosha/src/server/roomthread.cpp:64:1: warning:   when initialized here [-Wreorder]
../QSanguosha/src/server/roomthread.cpp: In member function ‘void RoomThread::run3v3(QList<ServerPlayer*>&, QList<ServerPlayer*>&, GameRule_, ServerPlayer_)’:
../QSanguosha/src/server/roomthread.cpp:324:75: error: no matching function for call to ‘GameRule::trigger(TriggerEvent, Room_&, ServerPlayer_&, QVariant)’
../QSanguosha/src/server/roomthread.cpp:324:75: note: candidate is:
In file included from ../QSanguosha/src/server/roomthread.cpp:4:0:
../QSanguosha/src/server/gamerule.h:13:18: note: virtual bool GameRule::trigger(TriggerEvent, Room_, ServerPlayer_, QVariant&) const
../QSanguosha/src/server/gamerule.h:13:18: note:   no known conversion for argument 4 from ‘QVariant’ to ‘QVariant&’
../QSanguosha/src/server/roomthread.cpp: In member function ‘void RoomThread::actionHulaoPass(ServerPlayer_, QList<ServerPlayer_>, GameRule_, int)’:
../QSanguosha/src/server/roomthread.cpp:457:83: error: no matching function for call to ‘GameRule::trigger(TriggerEvent, Room_&, ServerPlayer_&, QVariant)’
../QSanguosha/src/server/roomthread.cpp:457:83: note: candidate is:
In file included from ../QSanguosha/src/server/roomthread.cpp:4:0:
../QSanguosha/src/server/gamerule.h:13:18: note: virtual bool GameRule::trigger(TriggerEvent, Room_, ServerPlayer_, QVariant&) const
../QSanguosha/src/server/gamerule.h:13:18: note:   no known conversion for argument 4 from ‘QVariant’ to ‘QVariant&’
../QSanguosha/src/server/roomthread.cpp:470:75: error: no matching function for call to ‘GameRule::trigger(TriggerEvent, Room_&, ServerPlayer_&, QVariant)’
../QSanguosha/src/server/roomthread.cpp:470:75: note: candidate is:
In file included from ../QSanguosha/src/server/roomthread.cpp:4:0:
../QSanguosha/src/server/gamerule.h:13:18: note: virtual bool GameRule::trigger(TriggerEvent, Room_, ServerPlayer_, QVariant&) const
../QSanguosha/src/server/gamerule.h:13:18: note:   no known conversion for argument 4 from ‘QVariant’ to ‘QVariant&’
../QSanguosha/src/server/roomthread.cpp: In member function ‘void RoomThread::actionNormal(GameRule_)’:
../QSanguosha/src/server/roomthread.cpp:498:75: error: no matching function for call to ‘GameRule::trigger(TriggerEvent, Room_&, ServerPlayer_&, QVariant)’
../QSanguosha/src/server/roomthread.cpp:498:75: note: candidate is:
In file included from ../QSanguosha/src/server/roomthread.cpp:4:0:
../QSanguosha/src/server/gamerule.h:13:18: note: virtual bool GameRule::trigger(TriggerEvent, Room_, ServerPlayer_, QVariant&) const
../QSanguosha/src/server/gamerule.h:13:18: note:   no known conversion for argument 4 from ‘QVariant’ to ‘QVariant&’
make[1]: **\* [roomthread.o] Error 1
make[1]: Leaving directory `/home/hongwei/games/QSanguosha_build'
make: **\* [/home/hongwei/games/QSanguosha_build/QSanguosha] Error 2

**Comment by Blaskyy** [comment]
In file included from src/core/WrappedCard.h:4:0,
                 from src/core/player.h:5,
                 from src/core/structs.h:11,
                 from swig/sanguosha_wrap.cxx:1621:
src/core/card.h:130:25: warning: unused parameter ‘target’ [-Wunused-parameter]
     inline virtual void onNullified(ServerPlayer _target) const{ return; }
                         ^
swig/sanguosha_wrap.cxx: In member function ‘virtual const Card_ LuaFilterSkill::viewAs(const Card_) const’:
swig/sanguosha_wrap.cxx:2205:16: warning: converting ‘false’ to pointer type ‘const Card_’ [-Wconversion-null]
         return false;
                ^
swig/sanguosha_wrap.cxx: At global scope:
swig/sanguosha_wrap.cxx:55681:1: error: elements of array ‘const luaL_reg swig_commands []’ have incomplete type
 };
 ^
swig/sanguosha_wrap.cxx:55681:1: error: storage size of ‘swig_commands’ isn’t known
swig/sanguosha_wrap.cxx: In function ‘int luaopen_sgs(lua_State_)’:
swig/sanguosha_wrap.cxx:56819:19: error: ‘LUA_GLOBALSINDEX’ was not declared in this scope
   lua_pushvalue(L,LUA_GLOBALSINDEX);
                   ^
make: *_\* [sanguosha_wrap.o] Error 1

**Comment by iven** [comment]
@Blaskyy 
使用的是最新的代码么？试试先 cd swig; swig -c++ -lua sanguosha.i 再编译，还会有问题么？

**Comment by Blaskyy** [comment]
@iven 是最新的master分支, 试了还是不行~

**Comment by Paracel** [comment]
swig 2.0.9 plz

**Comment by pansz** [comment]
因为 Linux 中通常不可能那么快升级系统组件，因此恢复到可以支持 swig 1.3 的 lua5.1

fixed

**Comment by iven** [comment]
@Blaskyy 是该更新系统了，我这都 2.0.10 了…… 1.3 那是多少年前的版本啊……
