### ISSUE TITLE
Debian wheezy编译错误。

### ISSUE THREAD

**Issue by shouhuanxiaoji** [gaodayihao/QSanguosha#107]
../QSanguosha/src/core/card.h:130:25: warning: unused parameter ‘target’ [-Wunused-parameter]
In file included from ../QSanguosha/src/server/roomthread.h:10:0,
                 from ../QSanguosha/src/server/roomthread.cpp:1:
../QSanguosha/src/core/structs.h: In constructor ‘DamageStruct::DamageStruct(const QString&, ServerPlayer_, ServerPlayer_, int, DamageStruct::Nature)’:
../QSanguosha/src/core/structs.h:34:10: warning: ‘DamageStruct::by_user’ will be initialized after [-Wreorder]
../QSanguosha/src/core/structs.h:33:10: warning:   ‘bool DamageStruct::transfer’ [-Wreorder]
../QSanguosha/src/server/roomthread.cpp:64:1: warning:   when initialized here [-Wreorder]
../QSanguosha/src/server/roomthread.cpp: In member function ‘void RoomThread::run3v3(QList<ServerPlayer*>&, QList<ServerPlayer*>&, GameRule_, ServerPlayer_)’:
../QSanguosha/src/server/roomthread.cpp:324:75: error: no matching function for call to ‘GameRule::trigger(TriggerEvent, Room_&, ServerPlayer_&, QVariant)’
../QSanguosha/src/server/roomthread.cpp:324:75: note: candidate is:
In file included from ../QSanguosha/src/server/roomthread.cpp:4:0:
../QSanguosha/src/server/gamerule.h:13:18: note: virtual bool GameRule::trigger(TriggerEvent, Room_, ServerPlayer_, QVariant&) const
../QSanguosha/src/server/gamerule.h:13:18: note:   no known conversion for argument 4 from ‘QVariant’ to ‘QVariant&’
../QSanguosha/src/server/roomthread.cpp: In member function ‘void RoomThread::actionHulaoPass(ServerPlayer_, QList<ServerPlayer_>, GameRule_, int)’:
../QSanguosha/src/server/roomthread.cpp:457:83: error: no matching function for call to ‘GameRule::trigger(TriggerEvent, Room_&, ServerPlayer_&, QVariant)’
../QSanguosha/src/server/roomthread.cpp:457:83: note: candidate is:
In file included from ../QSanguosha/src/server/roomthread.cpp:4:0:
../QSanguosha/src/server/gamerule.h:13:18: note: virtual bool GameRule::trigger(TriggerEvent, Room_, ServerPlayer_, QVariant&) const
../QSanguosha/src/server/gamerule.h:13:18: note:   no known conversion for argument 4 from ‘QVariant’ to ‘QVariant&’
../QSanguosha/src/server/roomthread.cpp:470:75: error: no matching function for call to ‘GameRule::trigger(TriggerEvent, Room_&, ServerPlayer_&, QVariant)’
../QSanguosha/src/server/roomthread.cpp:470:75: note: candidate is:
In file included from ../QSanguosha/src/server/roomthread.cpp:4:0:
../QSanguosha/src/server/gamerule.h:13:18: note: virtual bool GameRule::trigger(TriggerEvent, Room_, ServerPlayer_, QVariant&) const
../QSanguosha/src/server/gamerule.h:13:18: note:   no known conversion for argument 4 from ‘QVariant’ to ‘QVariant&’
../QSanguosha/src/server/roomthread.cpp: In member function ‘void RoomThread::actionNormal(GameRule_)’:
../QSanguosha/src/server/roomthread.cpp:498:75: error: no matching function for call to ‘GameRule::trigger(TriggerEvent, Room_&, ServerPlayer_&, QVariant)’
../QSanguosha/src/server/roomthread.cpp:498:75: note: candidate is:
In file included from ../QSanguosha/src/server/roomthread.cpp:4:0:
../QSanguosha/src/server/gamerule.h:13:18: note: virtual bool GameRule::trigger(TriggerEvent, Room_, ServerPlayer_, QVariant&) const
../QSanguosha/src/server/gamerule.h:13:18: note:   no known conversion for argument 4 from ‘QVariant’ to ‘QVariant&’
make[1]: **\* [roomthread.o] 错误 1
make[1]: Leaving directory `/home/xiaoji/QSanguosha_build'
make: **\* [/home/xiaoji/QSanguosha_build/QSanguosha] 错误 2

**Comment by shouhuanxiaoji** [comment]
还有一个问题，现在太阳神三国杀最新版本是啥，春分版（0224）还是0610？

**Comment by WilliamShi** [comment]
0224在linux下編譯ok，但是0610在linux下編譯有問題，在windows下編譯ok

**Comment by pansz** [comment]
fixed 新编译错误，请重新测试。
