### ISSUE TITLE
git 版运行时错误

### ISSUE THREAD

**Issue by iven** [gaodayihao/QSanguosha#109]
单机启动，设置好各种选项后点确定，会弹出对话框“Lua 脚本错误”：

```
lua/ai/standard_cards-ai.lua:1064: '=' expected near 'end'
```

**Comment by yysfire** [comment]
这是因为新版AI将Lua升级至5.2.2，并添加continue语句，此语句是不被lua 5.1支持的。
可按照 http://lua-users.org/wiki/ContinueProposal 提供的方法将AI中出现continue语句的地方用repeat语句替换

**Comment by iven** [comment]
两边还不统一是闹哪样……果断链接到系统自带的 Lua 了。
