### ISSUE TITLE
陆逊加淑慎伏皇后死循环

### ISSUE THREAD

**Issue by WilliamShi** [gaodayihao/QSanguosha#111]
满血回合结束弃牌死循环了
![endlessloop](https://f.cloud.github.com/assets/2637940/811999/4891a03e-eee7-11e2-9bb4-d1c560f6c2b6.jpg)

**Comment by YanGuam** [comment]
有办法再现吗...

**Comment by WilliamShi** [comment]
編譯版本20130629，只要有陸遜就有這個問題，我後來又碰到了，只要選陸遜100%可重現

**Comment by WilliamShi** [comment]
最新版本都好了
