### ISSUE TITLE
Lua脚本错误

### ISSUE THREAD

**Issue by Blaskyy** [gaodayihao/QSanguosha#113]
lua/ai/standard_cards-ai.lua:1064: '=' expected near 'end'

➜  QSanguosha git:(master) ✗ ./QSanguosha 
Package New1v1Card cannot be loaded!
Package Special1v1 cannot be loaded!
Package Special1v1OL cannot be loaded!
Package NostalGeneral cannot be loaded!

![Lua脚本错误](http://i.imgur.com/FE6pPjT.png)

**Comment by WilliamShi** [comment]
因為缺省lua不帶continue，所以要自己改提示錯誤的幾個文件，我改了三個就好了，把if ... then continue end中的continue刪掉，把這個end後面整個for循環裡面的東西全部拷貝到剛才刪除的continue的地方並在前面加上else就可以了。不過好像可以下載一個lua的continue補丁，有了補丁就什麼都不用改

**Comment by Blaskyy** [comment]
soga,谢啦,我试下

**Comment by Blaskyy** [comment]
@WilliamShi 按你说的方法成功了~改了三个文件~
