### ISSUE TITLE
2013-06-10 tag 版本linux下编译错误，以前曾经好像编译通过的

### ISSUE THREAD

**Issue by WilliamShi** [gaodayihao/QSanguosha#114]
../QSanguosha/src/server/roomthread.cpp:324:75: error: no matching function for call to 'GameRule::trigger(TriggerEvent, Room_&, ServerPlayer_&, QVariant)'

**Comment by pansz** [comment]
完全 clean 一下再试试？

**Comment by pansz** [comment]
fixed
