### ISSUE TITLE
vs2010 build failed

### ISSUE THREAD

**Issue by WilliamShi** [gaodayihao/QSanguosha#119]
4>....\src\ui\roomscene.cpp(756): error C2065: 'infoPlane' : undeclared identifier
4>....\src\ui\roomscene.cpp(756): error C2228: left of '.width' must have class/struct/union

**Comment by Fsu0413** [comment]
我早知道了……主要问题我感觉是出在ready属性上……

**Comment by WilliamShi** [comment]
我改了一些代码，编译没有问题但是link还是有问题，link外部库的问题，我怀疑是lua升级导致

**Comment by WilliamShi** [comment]
自从8月26日之后就再也没有更新过了，因为每次编译不成功，今天想下决心编译下，结果编译过了，但是link还是有问题，哪位朋友帮帮忙啊，谢谢。错误信息如下：
1>Link:
1>     Creating library ....\Bin\QSanguosha.lib and object ....\Bin\QSanguosha.exp
1>moc_dashboard.obj : error LNK2001: unresolved external symbol "private: void __thiscall Dashboard::onCardItemDoubleClicked(void)" (?onCardItemDoubleClicked@Dashboard@@AAEXXZ)
1>....\Bin\QSanguosha.exe : fatal error LNK1120: 1 unresolved externals
1>
1>Build FAILED.
1>
1>Time Elapsed 00:01:58.48
========== Build: 0 succeeded, 1 failed, 3 up-to-date, 0 skipped ==========

**Comment by WilliamShi** [comment]
又改了改，编译link都ok了，运行时出现找不到文件lua/utilities.lua ，这个文件哪里找啊，网上也搜不到啊

**Comment by WilliamShi** [comment]
从这里 https://github.com/Paracel/QSanguosha-Para/blob/master/lua/utilities.lua
拷贝了一个utilities.lua终于可以玩了，但是貌似这个文件不大对头，机器好傻

**Comment by Fsu0413** [comment]
你可以去sanguosha.lua里面看看，应该是有关于这个文件的说明

**Comment by Paracel** [comment]
代码现在还在调整，AI应该有很多问题。。。

**Comment by WilliamShi** [comment]
请问哪个版本比较稳定一点8月26号之后的
在 2013-11-21 下午11:49，"Paracel" notifications@github.com写道：

**Comment by WilliamShi** [comment]
现在用下来觉得还可以，陆逊修复了，不知道李儒的bug好了没有，这个版本显示是2013年11月30号v2版本，不知道是不是准备在11月30号推出稳定版本呢，编译时间是11月21号，这个版本凌统旋风无法选择角色没办法发动。
