### ISSUE TITLE
编译时候sanguosha_wrap.cxx好多错误

### ISSUE THREAD

**Issue by WilliamShi** [gaodayihao/QSanguosha#124]
这个文件是自动生成的吧，需要升级什么工具之类的吗?
编译错误信息如下：
g++ -c -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -O2 -Wall -W -D_REENTRANT -DAUDIO_SUPPORT -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/lib/qt4/mkspecs/linux-g++ -I../QSanguosha -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include/QtSql -I/usr/include/QtDeclarative -I/usr/include -I../QSanguosha/include -I../QSanguosha/src/client -I../QSanguosha/src/core -I../QSanguosha/src/dialog -I../QSanguosha/src/package -I../QSanguosha/src/scenario -I../QSanguosha/src/server -I../QSanguosha/src/ui -I../QSanguosha/src/util -I../QSanguosha/src/jsoncpp/include -I../QSanguosha/include/fmod -I../QSanguosha/src/lua51 -I../QSanguosha/include/freetype -I. -I. -I../QSanguosha -I. -o sanguosha_wrap.o ../QSanguosha/swig/sanguosha_wrap.cxx
../QSanguosha/swig/sanguosha_wrap.cxx: In member function ‘virtual const Card\* LuaFilterSkill::viewAs(const Card_) const’:
../QSanguosha/swig/sanguosha_wrap.cxx:2394:16: warning: converting ‘false’ to pointer type ‘const Card_’ [-Wconversion-null]
../QSanguosha/swig/sanguosha_wrap.cxx: In function ‘int _wrap_CardsMoveOneTimeStruct_from_pile_names_set(lua_State_)’:
../QSanguosha/swig/sanguosha_wrap.cxx:26380:1: error: jump to label ‘fail’ [-fpermissive]
../QSanguosha/swig/sanguosha_wrap.cxx:26361:217: error:   from here [-fpermissive]
../QSanguosha/swig/sanguosha_wrap.cxx:26365:10: error:   crosses initialization of ‘size_t len’
../QSanguosha/swig/sanguosha_wrap.cxx:26380:1: error: jump to label ‘fail’ [-fpermissive]
../QSanguosha/swig/sanguosha_wrap.cxx:26358:187: error:   from here [-fpermissive]
../QSanguosha/swig/sanguosha_wrap.cxx:26365:10: error:   crosses initialization of ‘size_t len’
../QSanguosha/swig/sanguosha_wrap.cxx:26380:1: error: jump to label ‘fail’ [-fpermissive]
../QSanguosha/swig/sanguosha_wrap.cxx:26357:225: error:   from here [-fpermissive]
../QSanguosha/swig/sanguosha_wrap.cxx:26365:10: error:   crosses initialization of ‘size_t len’
../QSanguosha/swig/sanguosha_wrap.cxx:26380:1: error: jump to label ‘fail’ [-fpermissive]
../QSanguosha/swig/sanguosha_wrap.cxx:26356:172: error:   from here [-fpermissive]
../QSanguosha/swig/sanguosha_wrap.cxx:26365:10: error:   crosses initialization of ‘size_t len’
../QSanguosha/swig/sanguosha_wrap.cxx: In function ‘void SWIG_InitializeModule(void_)’:
../QSanguosha/swig/sanguosha_wrap.cxx:64099:21: warning: statement has no effect [-Wunused-value]
make[1]: **\* [sanguosha_wrap.o] Error 1
make[1]: Leaving directory `/home/hongwei/games/gdyh/QSanguosha_build'
make: **\* [/home/hongwei/games/gdyh/QSanguosha_build/QSanguosha] Error 2

**Comment by WilliamShi** [comment]
玩不了了，哪位兄弟帮帮忙看看这个问题啊，谢谢

**Comment by Fsu0413** [comment]
用最后一个Paracel的代码编译

**Comment by WilliamShi** [comment]
现在用tag 2013-12-10编译也通不过了

**Comment by Fsu0413** [comment]
你是用什么编译的^

**Comment by WilliamShi** [comment]
就make啊，以前一直o k的
2014-1-7 下午11:28于 "Fsu0413" notifications@github.com写道：

**Comment by Fsu0413** [comment]
怎么make的

**Comment by WilliamShi** [comment]
就是在QSanguosha目录下敲make，以往一直工作的，有时候有些小问题自己改改都能成功编译出来可以执行的QSanguosha

**Comment by WilliamShi** [comment]
刚刚pull之后编译顺利通过，谢谢

**Comment by Fsu0413** [comment]
好吧……我一直用VS

**Comment by WilliamShi** [comment]
vs我一直编译都没问题

**Comment by pansz** [comment]
swig 本身生成的代码有问题，目前已经暂时补丁修复，后续我会想个其他的办法解决此问题。
