### ISSUE TITLE
一张牌不能离手的bug……

### ISSUE THREAD

**Issue by Procellarum** [gaodayihao/QSanguosha#15]
呃还是曹植
落英收了一张梅花杀（上一个issue里重复收的一张）
有连弩
用该杀指定目标会出现指示线，有杀的效果
但是不会离手
弃牌阶段弃不掉
嗯就是这样

**Comment by Procellarum** [comment]
补充
响应南蛮有效果，仍然不能出手

**Comment by hejun442001** [comment]
卡牌bug 原因未知 （此bug原版就有）
