### ISSUE TITLE
found bug in QSanInvokeSkillDock::update()

### ISSUE THREAD

**Issue by hejun442001** [gaodayihao/QSanguosha#2]
I found bug in QSanInvokeSkillDock::update() 

at src/ui/qsanbutton.cpp L390 : " int btnWidth = _m_width / btnNum[i] "
program crashed when btnNum[i]  equals zero.
it will happen when player lost all skills.

I fixed the bug in this commit:
https://github.com/hejun442001/QSanguosha/commit/686129feb5c0ca35dced20e9bf4b026c9c3a0bdc

(btw: I cannot send pull request to this project, so I send this issues)

**Comment by gaodayihao** [comment]
Thank you for your feedback.
We also found the problem, but I tend to use this way to solve:

at: src\ui\qsanbutton.h L144: update();  
modified as: if (!_m_buttons.empty()) update();

**Comment by gaodayihao** [comment]
I think this solution is safer and easier to read.

Thanks for your feedback again.

**Comment by hejun442001** [comment]
最后决定在我的分支中用 @gaodayihao 的方案了
这里呢？

**Comment by gaodayihao** [comment]
都没用…………因为都有点笨…………: )

**Comment by hejun442001** [comment]
为什么？   55555555555555555~~~~~~~~~~~~
