### ISSUE TITLE
Assertion fail when client receive the following packet

### ISSUE THREAD

**Issue by pansz** [gaodayihao/QSanguosha#29]
RX: [782,0,1,23,["amazing_grace","sgs5","sgs5"]]
QSanguosha: src/jsoncpp/src/json_value.cpp:692: const char\* Json::Value::asCString() const: Assertion `type_ == stringValue' failed.
Aborted (core dumped)

RX is the packet received.

**Comment by ghost** [comment]
Reading the source code and the package you posted, I couldn't believe that the assertion is failed. This package is sent by the server to ask the client whether to play an "invincible" card against sgs5's "amazinggrace". But all three parameters are strings, therefore shouldn't fail the assertion. I would be really surprised if this assertion fail... Can you upload the dump file in your dmp directory?

**Comment by pansz** [comment]
well, the core file is 209M... do you really want it?

Server often core dumps and things may be clearer when I print all RX and TX packets in nativesocket.cpp.

I'll re-compile with debug and try more.

**Comment by pansz** [comment]
I'll give you a core dump backtrace:

Core was generated by `./QSanguosha'.
Program terminated with signal 6, Aborted.
#0  0x00007fea01eba445 in __GI_raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
64      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007fea01eba445 in __GI_raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00007fea01ebdbab in __GI_abort () at abort.c:91
#2  0x00007fea01eb310e in __assert_fail_base (fmt=<optimized out>, assertion=0x7a654d "type_ == stringValue", 
    file=0x7a6660 "src/jsoncpp/src/json_value.cpp", line=<optimized out>, function=<optimized out>) at assert.c:94
#3  0x00007fea01eb31b2 in __GI___assert_fail (assertion=0x7a654d "type_ == stringValue", file=0x7a6660 "src/jsoncpp/src/json_value.cpp", 
    line=692, function=0x7a6d00 "const char\* Json::Value::asCString() const") at assert.c:103
#4  0x00000000006a0acb in Json::Value::asCString() const ()
#5  0x00000000006693c9 in QSanRoomSkin::getGeneralPixmapPath(QString const&, QSanRoomSkin::GeneralIconSize) const ()
#6  0x0000000000434022 in Client::askForNullification(Json::Value const&) ()
#7  0x000000000043212d in Client::processServerRequest(QSanProtocol::QSanGeneralPacket const&) ()
#8  0x000000000043dc65 in Client::processServerPacket(char const_) ()
#9  0x000000000073b7d1 in Client::qt_static_metacall(QObject_, QMetaObject::Call, int, void**) ()
#10 0x00007fea02dfd281 in QMetaObject::activate(QObject_, QMetaObject const_, int, void**) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#11 0x000000000077d18d in ClientSocket::message_got(char const_) ()
#12 0x000000000067ded0 in NativeClientSocket::getMessage() ()
#13 0x00007fea02dfd281 in QMetaObject::activate(QObject_, QMetaObject const_, int, void__) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#14 0x00007fea0320c68f in ?? () from /usr/lib/x86_64-linux-gnu/libQtNetwork.so.4
#15 0x00007fea03214201 in ?? () from /usr/lib/x86_64-linux-gnu/libQtNetwork.so.4
#16 0x00007fea03657894 in QApplicationPrivate::notify_helper(QObject_, QEvent_) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#17 0x00007fea0365c713 in QApplication::notify(QObject_, QEvent_) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#18 0x00007fea02de8e9c in QCoreApplication::notifyInternal(QObject_, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#19 0x00007fea02e17a97 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#20 0x00007fea0067ad53 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007fea0067b0a0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007fea0067b164 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007fea02e183bf in QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#24 0x00007fea036ffd5e in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#25 0x00007fea02de7c82 in QEventLoop::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#26 0x00007fea02de7ed7 in QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#27 0x00007fea02decf67 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#28 0x000000000042bd56 in main ()

**Comment by ghost** [comment]
@gaodayihao Another issue with that stupid nullification prompt box. Please
help remove it as soon as possible...

2012/7/17 pansz <
reply@reply.github.com
