### ISSUE TITLE
不明真相的崩溃

### ISSUE THREAD

**Issue by BeginnerSlob** [gaodayihao/QSanguosha#3]
2人局（非KOF），我主孙权，对面翼曹仁， 曹仁结束回合（已经出现了回合分界线），游戏崩溃。

**Comment by ghost** [comment]
Does this issue still exist?

**Comment by BeginnerSlob** [comment]
i don't know,it seems that each skill in LingPackage will make the program break.

**Comment by ghost** [comment]
@BeginnerSlob Do you have the dump file?

**Comment by BeginnerSlob** [comment]
@yinlin09 No,it is too ealry to I know how to save a dump file.
