### ISSUE TITLE
Linux下面编译失败

### ISSUE THREAD

**Issue by gutenye** [gaodayihao/QSanguosha#30]
```
which: invalid option -- 's'
/usr/bin/qmake
which: invalid option -- 's'
/usr/bin/swig
Generate lua binding code
Generating Makefile using project file
WARNING: Failure to find: src/core/statistics.cpp
WARNING: Failure to find: src/core/statistics.h
Compile it
make: *** No rule to make target `src/core/statistics.cpp', needed by `statistics.o'.  Stop.
Updating '/home/guten/game/nsanguosha/sanguosha.qm'...
    Generated 708 translation(s) (708 finished and 0 unfinished)
Well, everything is OK. You can run it with ./QSanguosha
```

**Comment by pansz** [comment]
This is because: 'which -s' is not a valid option.

I don't know why, probably Moligaloo could make which -s work on ArchLinux.

For me, which -s does not work on Ubuntu.

remove the "-s" ?

**Comment by pansz** [comment]
32a2f50ecb32e1fb2a185fd594051e3c05340f4d changed it into which, it should work on Debian/Ubuntu then.

**Comment by gutenye** [comment]
still get error. need https://github.com/GutenYe/QSanguosha/commit/71e6b01f8fe59569863b5b4630ad3dad26aaeba5 this fix, but I can't do a pull-request. 

which fix below error

```
Generating Makefile using project file
WARNING: Failure to find: src/core/statistics.cpp
WARNING: Failure to find: src/core/statistics.h
Compile it
make: *** No rule to make target `src/core/statistics.cpp', needed by `statistics.o'.  Stop.
```

**Comment by pansz** [comment]
That is not linux-related... it is just someone forget to commit the right file.

I've uploaded a linux.mk, which supports shadow-build and is more linux-friendly.

First, clean the garbage created by compile.sh with make distclean.

Then use it with make -f linux.mk

**Comment by gutenye** [comment]
thanks for the linux.mk  file, but still got

```
make[1]: *** No rule to make target `src/core/statistics.cpp', needed by `statistics.o'.  Stop.
make[1]: Leaving directory `/home/user/game/qsanguosha_build'
make: *** [/home/user/game/qsanguosha_build/QSanguosha] Error 2
```

**Comment by pansz** [comment]
@yinlin09 for statistics.cpp problem: you removed the file but forget to removed it in QSanguosha.pro (also for statistics.h)

**Comment by ghost** [comment]
@GutenYe @pansz if you wish to join our develop team, please add QQ group 236522670. I'll remove this comment after you've all seen this.

**Comment by gutenye** [comment]
@yinlin09 thanks. I'm interested.

**Comment by pansz** [comment]
@yinlin09  I'm in the 190147900 and you still don't know who I am?
我希望能够以这个群为主，不然就失去了建这个群的意义。或者说我被刻意孤立在可用群之外？
