### ISSUE TITLE
张角八卦阵判定中应不能使用八卦阵发动鬼道

### ISSUE THREAD

**Issue by BeginnerSlob** [gaodayihao/QSanguosha#34]

**Comment by pansz** [comment]
其实这是一个系列的体系性的问题。就是当前正在作用的物件是否被锁定。

关羽能不能用武圣，把已经装备的麒麟弓杀距离5的人，这也是一样的道理：麒麟弓的攻击范围效果正在应用中，你就不能把麒麟弓作为代价用出去。

要改，需要的是体系上的，一致的修改。到处打补丁就是天天都在忙。
