### ISSUE TITLE
贯石斧UI需要调整

### ISSUE THREAD

**Issue by ghost** [gaodayihao/QSanguosha#36]
贯石斧应该在提示弃牌时自动处于选中状态，考虑一下是贯石的技能归类不对还是UI的问题，如果是前者则修改服务器端

**Comment by BeginnerSlob** [comment]
反馈上来贯石斧还有一个BUG就是选择1张牌点取消就会崩，
而在我测试的时候根本选不了牌。不知道是什么原因。
