### ISSUE TITLE
Figure out why there is an unreferenced CompareByActionOrder in gamerule.cpp

### ISSUE THREAD

**Issue by ghost** [gaodayihao/QSanguosha#4]
Our github history has been screwed up. So we are not able to find who's "guilty" for each line of code in current repository. Specifically I find that there is an unreferenced CompareByActionOrder function in gamerule.cpp. It's originally called by case CardUsed of gamerule::trigger. Figure out if the original sorting is really necessary; i yes, add it back; if not, delete the CompareByActionOrder function.

**Comment by hejun442001** [comment]
我的意见：
把CompareByActionOrder()放到一个公用的头文件中，并删除散在各处的相关副本。
