### ISSUE TITLE
found bug:神周瑜发动业炎时程序崩溃

### ISSUE THREAD

**Issue by hejun442001** [gaodayihao/QSanguosha#5]
bug现象 神周瑜发动原大业炎时程序崩溃
bug频率：必现（AI和玩家都会）

我调试发现 崩溃点在  CompareByActionOrder （）函数中的   a->getRoom();   上。 （调试时传入的a并非合理值也非NULL。）

**Comment by gaodayihao** [comment]
请说明一下当时崩溃的重现具体重现方法……因为我这边重现不了

**Comment by gaodayihao** [comment]
嗯，知道问题所在了~~~的确有这个问题，虽然我这里不是总会出现 ：）

感谢反馈~~~ ：）
