### ISSUE TITLE
Hard-coded font name cause missing font in Linux.

### ISSUE THREAD

**Issue by pansz** [gaodayihao/QSanguosha#62]
我们的程序提供了 simkai 以及 simli 两个字体。

但是在 skins/*.json 中，我发现不少地方使用了 simsun 以及 Arial 字体，而这个字体并没有随程序提供，这就造成了很多地方不正常显示的问题。

为了允许 Linux 中正常显示，我们可能有如下选择：
1。将所有 simsun 以及 Arial 字体替换成我们提供的 simkai 以及 simli。
2。修改  layout 为 Linux 单独制作一套 layout.json 文件。
3。增加字体以适应需求。保证所有被指定的字体都在 font 目录中提供。

请 @Paracel  @GutenYe  @BeginnerSlob 考虑一下。

**Comment by ShaunDonle** [comment]
Its not a serious problem, the first 2 choices are both satisfied. But I prefer to the choice that making another additional copy of this for Linux OS

**Comment by Paracel** [comment]
1会影响显示效果

**Comment by gutenye** [comment]
选第3个， 把simsun, Arial字体也加入到程序里面。

**Comment by pansz** [comment]
其中一个担忧是现在字体已然不少，整个游戏的包已然不小，增加字体回额外的增加整个程序包的大小，而这本来完全没有必要。（尤其是楷体只在一个地方使用，却为了这个字体占用了 12M 空间，是否有些浪费？）

关于增加字体的方案，我的建议是使用 msyh 来替代 simsun+Arial，理由也很简单，其实我们只需要 simsun 的中文字体以及 Arial 的英文字体，而 msyh 无论中文英文效果都不错，所以一个可以替代两个。

实际上，msyh 以及 simsun 存在的目的是为了提供小点阵下的中文。Arial 存在的目的是为了提供不等宽英文字体。

这里 simli simkai 都是等宽字体，因此 sim 系列的英文其实是完全不可用的。去掉 simkai 修改为 simli/simsun/msyh 是否有问题？

另外游戏右侧的日志栏，似乎根本没有使用随程序提供的字体，而是使用了系统字体，如果可以在其他地方也使用系统字体，则就可以不需要随程序提供了。

**Comment by pansz** [comment]
I had updated the source.

注意这次增加了 msyh.ttf ，但是 windows 版本制作程序包时可以不包括它，因为只在 linux 和 mac 中用到。

这个算是在不增加 windows 发行版尺寸的情况下做出的改良了。

**Comment by iven** [comment]
@pansz WinXP 不自带雅黑的吧……

**Comment by pansz** [comment]
@iven 现在对 Linux 跟 Windows 使用了不同的 style。
Windows 版本的 style 仍然依赖 simsun 和 arial。
Linux 版本依赖雅黑。

所以只需要在 Linux 版本中提供雅黑即可。
