### ISSUE TITLE
Are there some guys interested in AI learning?

### ISSUE THREAD

**Issue by ShaunDonle** [gaodayihao/QSanguosha#64]
My design  is about a new framework of AI, it uses the thesis of partially observable multi-agent system for reinforcement learning. And I use Q learning for the learning process. Now I have to design the Q value function, reward function and the design of all the states expression.I have to say that the design is so complicated that I cannot complete all these things in a short term, I hope somebody may have interests about AI and I can briefly present the working theory which can let you guys program the framework individually so that can help me to do the work more effectively.

**Comment by pansz** [comment]
You can just present the theory in the [Wiki page](https://github.com/gaodayihao/QSanguosha/wiki)  and see if anyone interested in it.
