### ISSUE TITLE
1月24日编译失败

### ISSUE THREAD

**Issue by crazygao** [gaodayihao/QSanguosha#84]
/home/philip/QSanguosha/src/package/god.cpp:1445: error: 'WushenSlash' was not declared in this scope
谁编译过了可以知会一下么～～

**Comment by crazygao** [comment]
更新：注释WushenSlash之后
skill = new HalberdSkill;
HalberdSkill不是TriggerSkill 的子类，报错……

**Comment by Paracel** [comment]
thx
