### ISSUE TITLE
顺手牵羊和铁索连环

### ISSUE THREAD

**Issue by nutari** [gaodayihao/QSanguosha#89]
在顺手牵羊里有这么一段，感觉顺应该是和武器无关的吧
if (Self->getWeapon() && subcards.contains(Self->getWeapon()->getId())){
        const Weapon *weapon = qobject_cast<const Weapon *>(Self->getWeapon()->getRealCard());
        rangefix += weapon->getRange() - 1;
    }
这样如果我拿2+射程的武器当顺，距离1的也顺不到了……

然后铁索的feasible，在filter里的目标数量和targetmodskill挂钩，但是feasible里还是限制了最多2个，应该是忘了吧

**Comment by Paracel** [comment]
好吧习惯性当攻击范围了= =

**Comment by Paracel** [comment]
另外锦囊额外目标的问题我也改下吧，不过真要实现还是会有bug。。。
