### ISSUE TITLE
关于新版的一些问题。

### ISSUE THREAD

**Issue by nutari** [gaodayihao/QSanguosha#90]
1.在trigger技上挂view_as_skill的时候，如果是在出牌阶段主动使用的情况下，你必须把view_as_skill也添加给武将，否则按钮会一直是灰色的（然后可以隐藏一个
2.targetmodskill里关于杀的距离，实际上只有维持不变和无限而已，感觉应该是可以加在canSlash或者getAttackRange里的
3.使用锁定视为技（武魂，禁酒）打出杀的时候，发动朱雀会导致打出去一张无色的火杀，不会用出去你手中的牌，然后你也不能干其他事只能托管结束。先使用朱雀的话没有这个问题。

**Comment by haveatry823** [comment]
程序的事情， @Paracel  吧。

不过，nutari ,不知道你对 ai 是否有兴趣， 这个版本的的AI项目地址是
https://github.com/haveatry823/QSanguoshaAI

目前是五六个lua爱好者在维护， 急需你这种懂 lua 的人才进来一起撸

@nutari

**Comment by Paracel** [comment]
23了解
1你需要将ViewAsSkill的命名与TriggerSkill保持一致
