### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by ibicdlcod** [gaodayihao/QSanguosha#93]
room.cpp 4737:

reason.m_reason = is_preview ? CardMoveReason::S_REASON_PREVIEWGIVE : CardMoveReason::S_REASON_GIVE; // nasty hack only

./debug\room.o:E:\GitHub\QSanguosha-build-Desktop/../QSanguosha/src/server/room.cpp:4737: undefined reference to `CardMoveReason::S_REASON_PREVIEWGIVE'
./debug\room.o:E:\GitHub\QSanguosha-build-Desktop/../QSanguosha/src/server/room.cpp:4737: undefined reference to`CardMoveReason::S_REASON_GIVE'
collect2: ld returned 1 exit status

**Comment by BeginnerSlob** [comment]
= =never meet this strange error..

**Comment by ibicdlcod** [comment]
this error make debug mode virtually unusable.

**Comment by ibicdlcod** [comment]
And then you set breakpoint and won't work. ARRRRRGH!

**Comment by haveatry823** [comment]
try clean and rebuild

**Comment by ibicdlcod** [comment]
every time I use the public computer I rebuilds with clean environment, and error persists.

**Comment by BeginnerSlob** [comment]
@ibicdlcod But when using VS, the breakpoint is useful even if it is release MODE
