### ISSUE TITLE
报个客户端计时条的bug

### ISSUE THREAD

**Issue by adamhj** [gaodayihao/QSanguosha#98]
以下基于0224版本

bug现象如下：出牌阶段，使用ViewAsSkill的时候，点技能，然后点取消，计时条会重置，并且计时条走的速度会加快，反复几次计时条会走得和飞一样，而且这种情况之后会一直存在，出牌阶段时间会变得很短。

这里面涉及两个问题：
第一个是在TimedProgressBar::show()里，startTimer前并未对m_timer作检查，所以如果连续两次调用show()之间未调用过hide()的话，前一个timer未销毁后一个timer又新建了，这个计时条上就会出现多个timer导致timerEvent()额外触发，结果就是计时条走得速度加快了，并且因为前面的timer句柄丢失了所以他们会一直存在直到游戏结束
patch见https://github.com/adamhj/QSanguosha/commit/70c8b5fe80c5281281e606a2c36daf78964ac21e

第二个问题是我认为取消ViewAsSkill的时候不该重置计时条，因为实际上服务器端也有计时，即使我反复点技能-取消，实际上到了出手时间后服务器依然会强制弃牌，那么这个重置计时条的动作就显得没有意义了，重置计时条反而让玩家无法正确的获知剩余的出牌时间
patch见https://github.com/adamhj/QSanguosha/commit/872d03b89247b1c0ecb7bb6e16a93699e649449e

**Comment by Paracel** [comment]
好吧，因为一直都是无时间限制单机玩所以没注意到这个问题。。。下次合并代码的时候会修复。。。
